### ISSUE TITLE
No helper.js file in repo

### ISSUE THREAD

**Issue by Palmer-JC** [v-kiniv/kinect-js#2]
Was wondering where this file referenced in readme is?

**Comment by v-kiniv** [comment]
Actually, this is part of a proprietary project, so you wouldn't be able to use it without server application.

**Comment by grischka** [comment]
Too bad this looked really promising as most kinect packages aren't maintained anymore :/ Any plans to publish server application?

**Comment by Palmer-JC** [comment]
I made my own https://github.com/Palmer-JC/KinectToJSON

Directly uses the Kinect SDK, so it is Windows only.  Do not remember what this uses.
